# Generated by Django 3.2.9 on 2021-11-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='valor_estoque'),
        ),
    ]
