# Generated by Django 3.2.9 on 2021-11-09 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0002_auto_20211107_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
            ],
            options={
                'verbose_name': 'estoque saida',
                'verbose_name_plural': 'estoque saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
        migrations.AlterModelOptions(
            name='estoqueentrada',
            options={'verbose_name': 'estoque entrada', 'verbose_name_plural': 'estoque entrada'},
        ),
        migrations.AlterField(
            model_name='estoque',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saida')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='saldo',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
